# -*- coding: utf-8 -*-
"""1_Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZvH1Ruc_9CycKnP95EdFBtV80Le8OL2Z

# **1. Data Preprocessing**
- [Dataset Download](https://www.kaggle.com/uciml/sms-spam-collection-dataset)

## 1-1. 데이터 확인

우선, kaggle에서 제공하는 데이터셋을 다운받습니다.
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
# %matplotlib inline
import matplotlib.pyplot as plt
import urllib.request

urllib.request.urlretrieve("https://raw.githubusercontent.com/mohitgupta-omg/Kaggle-SMS-Spam-Collection-Dataset-/master/spam.csv", filename="spam.csv")
data = pd.read_csv('spam.csv',encoding='latin1')

print('총 데이터 수 :',len(data))

"""우선 데이터 확인을 위해 기존 데이터에서 **상위 10개**만 추출하여 확인해봅니다."""

data[:10]

"""## 1-2.불필요한 열 제거

불필요한 열 : `Unnamed: n`

위 3개의 열은 텍스트 분류를 진행하기엔 불필요한 열입니다.

위 3개의 열을 삭제하고 2개의 열(`v1`,`v2`)를 (`category`, `text`)로 변경합니다.
"""

data = data[data.columns[:2]] # 두열만 가져온다. 
data.columns = ['category', 'text']

data

"""해당 데이터의 정보 확인"""

data.info()

"""`null`값 확인"""

data.isnull().values.any()

"""중복 데이터 확인"""

data['text'].nunique(), data['category'].nunique()

df = pd.DataFrame(data)
duplicatedDF = df[df.duplicated()]
print(duplicatedDF)

"""5,572개 중  `403`개의 중복 데이터가 존재한다는 것을 확인하였습니다."""

data.drop_duplicates(subset=['text'], inplace=True)

df = pd.DataFrame(data)
print(df)  # 출력 DataFrame

